version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: 'cargo'
    directory: '/native/comrak_nif'
    schedule:
      internal: 'weekly'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
